// Generated by LiveScript 1.2.0
(function(){
  Reveal.initialize({
    control: true,
    progress: true,
    history: true,
    center: true,
    theme: 'sky',
    transition: 'default',
    dependencies: [
      {
        src: 'reveal.js/lib/js/classList.js',
        condition: function(){
          return !document.body.classList;
        },
        async: true
      }, {
        src: 'reveal.js/lib/js/classList.js',
        condition: function(){
          return !document.body.classList;
        },
        async: true
      }, {
        src: 'reveal.js/plugin/highlight/highlight.js',
        condition: function(){
          return !document.body.classList;
        },
        async: true
      }
    ]
  });
}).call(this);
